version: '3.1'

services:
  db:
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    image: mariadb:10.3
    restart: always
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: db_uscc_chatbot
    # ports:
    #   - 3306:3306

  phpmyadmin:
    image: phpmyadmin
    restart: always
    # ports:
    #   - 8005:80
    environment:
      PMA_HOSTS: db
    depends_on:
      - db

  frontend:
    build: ./frontend
    restart: always
    # ports:
    #   - 8080:8080
    # volumes:
    #   - ./frontend:/app
    depends_on:
      - db

  backend:
    build: ./backend
    restart: always
    # ports:
    #   - 5000:5000
    volumes:
      - ./backend:/app
    depends_on:
      - db
  
  nginx:
    image: nginx:1.20.1
    restart: always
    volumes:
      - ./nginx_setting:/etc/nginx/
    depends_on:
      - backend
      - frontend
    ports:
      - 8009:80
